name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Immunisation-History-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    apigee_deployments:
      - environment: internal-dev
        secret_file_ids:
          - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
          - ptl/app-credentials/jwt_testing/non-prod/ID_TOKEN_NHS_LOGIN_PRIVATE_KEY
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              e2e_tests: true
              smoke_tests: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: internal-qa
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: ref
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: dev
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: int
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: prod
        make_spec_visible: true
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
