variables:
  service_name: immunisation-history
  short_service_name: ih
  service_base_path: immunisation-history
  product_display_name: Immunisation History
  product_description: ' '
  spec_file: immunisation-history.json
