# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Innunisation History API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
x-nhs-api-spec-guid: 1b22efff-7b41-4fa0-9146-dc87686a7b5c
info:
  version: 1.0.0
  title: Immunisation History - FHIR API
  license:
    name: MIT
  contact:
    name: NHS Digital API Management
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  description: |
    ## Overview
    Use this API to access a patient’s immunisation history.

    You can:
    - get a patient's coronavirus (COVID-19) immunisation history, based on their NHS number

    You cannot currently use this API to:
    - get details of other types of immunisation
    - get the immunisation history for a specific date range

    You get the following data:
    - immunisation event details
    - patient demographic details, as captured at the point of immunisation

    The patient demographic details might differ from those held in the [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/demographics).
    To get demographic details from PDS, use the [Personal Demographics Service FHIR API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir).
    
    ### Data availability, timing and quality
    All immunisation records are verified to ensure the NHS number is correct before making them available via the API.
    
    In most cases this is automatic, and the record is available within 48 hours of the immunisation event, sometimes sooner.
    
    Where automated NHS number verification fails, we verify the NHS number manually, which can take longer.
    
    In a very small number of cases, we are unable to verify the NHS number, and we do not make the immunisation record available at all.

    ## Who can use this API
    This API:
    - is only for use by patient-facing applications
    - is only for non-clinical use
    - can only be used where there is a legal basis to do so
    
    Make sure you have a valid use case before you go too far with your development.
    To do this, [contact us](https://digital.nhs.uk/developer/help-and-support).

    You must do this before you can go live (see ‘Onboarding’ below).
    
    ## API status and roadmap    
    
    ### Status
    This API is in [private beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:
    - it's available in production but only to a limited number of connecting applications
    - it's more stable, but might still be subject to minor breaking changes
    
    If you would like to be involved in our beta programme, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    ### Roadmap
    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?tag=immunisation-history-api).

    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Service level
    
    This API is a platinum service, meaning it is operational and supported 24 x 7 x 365.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).
    
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).

    It also conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, and use US spellings, for example `/Immunization` not `/immunisations`
    - array names are singular, for example `entry` not `entries` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.
    
    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).
    
    ## Security and authorisation

    This API offers two access modes: User restricted &amp; Application restricted.

    ### User restricted

    * [Guides and Documentation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis)
    * [Authentication and Authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation)
    * for user-restricted the end user must be a patient
    * the end user must have their identity verified to 'high' (P9) level
    * the NHS number in the request must match the NHS number in the NHS login account

    ### Application restricted

    * [Guides and Documentation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis)
    * [Authentication and Authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis)
    * the calling application must strongly authenticate the end user using NHS login

    ## Environments and testing
    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/immunisation-history/FHIR/R4/`     |
    | Integration test  | `https://int.api.service.nhs.uk/immunisation-history/FHIR/R4/`         |
    | Production        | Not yet available                                                      |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is open access, so does not allow you to test authorisation

    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:
    
    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/b7dfde415e5726658d09)
    
    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    * is for formal integration testing
    * includes authorisation
    
    It also includes ready-to-use [immunisation history test data](https://digital.nhs.uk/developer/api-catalogue/immunisation-history-fhir/immunisation-history-fhir-api-test-data).
    
    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).
    
    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.

    Details to follow.
servers:
  - url: 'https://sandbox.api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Production environment.
paths:
  /Immunization:
    get:
      summary: Get immunisation history
      operationId: get-immunisation-history
      description: |
        Given an NHS number, get the patient's immunisation history.
        Also returns the patient's demographic details, as captured at the point of immunisation.
        
        ## Sandbox testing
        You can test the following scenarios in our sandbox environment:
        
        | Scenario                      | Request                                                              | Response                                   |
        | ----------------------------- | -------------------------------------------------------------------- | ------------------------------------------ |
        | Immunisation history found    | `patient.identifier`=`https://fhir.nhs.uk/Id/nhs-number\|9000000009` | HTTP Status 200 with immunisation data in response body |
        | No immunisations found        | `patient.identifier`=`https://fhir.nhs.uk/Id/nhs-number\|9000000033` | HTTP Status 200 with empty bundle in response body |
        | Bad Request                   | `patient.identifier`= anything else                                  | HTTP Status 400 Bad Request |


        You can try out the sandbox using the 'Try this API' feature on this page.

        Alternatively, you can try out the sandbox using our Postman collection:
    
        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/b7dfde415e5726658d09)
      parameters:
        - name: patient.identifier
          in: query
          description: |
            The patient's NHS number.
            Expressed as `<type>|<value>` where `<type>` must be `https://fhir.nhs.uk/Id/nhs-number` and `<value>` must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
            example: "https://fhir.nhs.uk/Id/nhs-number|9000000009"
        - name: procedure-code:below
          in: query
          description: |
            Parent SNOMED immunisation procedure code.
            For example, `90640007`, which is the parent code for all COVID-19 vaccinations.
          required: true
          schema:
            type: string
            example: "90640007"
            description: Parent SNOMED code for all COVID-19 vaccinations.
        - name: _include
          in: query
          description: |
            Specifies other resources to be included in the response along with the immunisations.
            Must be `Immunization:patient`, which will include patient demographic details.
          required: true
          schema:
            type: string
            example: "Immunization:patient"
        - name: Authorization
          in: header
          description: |
            An OAuth 2.0 bearer token, obtained using our [NHS login pattern](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation).
          required: true
          schema:
            type: string
            format: '^Bearer\ [[:ascii:]]+$'
            example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'            
        - name: X-Correlation-ID
          in: header
          required: false
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.
            
            Mirrored back in a response header.
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
      responses:
        '200':
          description: |
            The request was valid, and the response contains immunisation history and associated patient details.
            If there are no immunisations for the given NHS number, the response bundle will be empty.
          headers:
            X-Correlation-Id:
              $ref: components/schemas/XCorrelationId.yaml
          content:
            application/fhir+json:   
              schema:
                $ref: "components/schemas/Bundle.yaml"
              example:
                $ref: "components/examples/Immunization.json"
        '4XX':
          description: |
            An error occurred as follows:
            
            | HTTP status | Error code                 | Description |
            | ----------- | -------------------------- | --------------------------------------------- |
            | 400         | `processing`               | Missing or invalid NHS number |
            | 400         | `processing`               | Missing or invalid parent SNOMED code |
            | 401         | `processing`               | Missing or invalid ID token |
            | 401         | `processing`               | Missing or invalid OAuth 2.0 bearer token |
            | 401         | `processing`               | NHS number in request doesn't match NHS number in NHS login account |
            
            For details see the `diagnostics` field.
            
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome.yaml'
              example:
                $ref: 'components/examples/OperationOutcome.json'
# components object must be present for spec rendering to work in Bloomreach, even if the spec has no components
components:
  parameters:
    Dummy:
      name: dummy
      in: path
      description: Dummy.
      required: true
      schema:
        type: string
        example: "DUMMY"
  schemas:
    Patient:
      $ref: components/schemas/Patient.yaml
  examples:
    Dummy:
      summary: Dummy example
      value:
        resourceType: Dummy
        issue:
          - severity: error
            code: value
            details:
              coding:
                - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                  version: '1'
                  code: INVALID_RESOURCE_ID
                  display: Resource Id is invalid
