# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Innunisation History API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
x-nhs-api-spec-guid: 1b22efff-7b41-4fa0-9146-dc87686a7b5c
info:
  version: 1.0.0
  title: Immunisation History - FHIR API
  license:
    name: MIT
  contact:
    name: NHS Digital API Management
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  description:
    # Overview
    TBC
    
    # Who can use this API
    TBC
    
    # API status and roadmap    
    TBC
    
    # Technology
    TBC
    
    # Network access
    TBC
    
    # Security and authorisation
    TBC
    
    # Environments and testing
    TBC
    
    # Onboarding
    TBC
servers:
  - url: 'https://sandbox.api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/immunisation-history/FHIR/R4'
    description: Production environment.
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:   
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
