const HTTP_STATUS = {
  BAD_REQUEST: 400,
  OK: 200
};

const API_VERSIONS = {
  V1: '1.0',
  V2: '2.0'
};

const DEFAULT_VERSION = API_VERSIONS.V1;

exports.HTTP_STATUS = HTTP_STATUS;
exports.API_VERSIONS = API_VERSIONS;
exports.DEFAULT_VERSION = DEFAULT_VERSION;
